name: on-prem-agent
services:
  on-prem-agent:
    image: prismaticio/on-prem-agent:1.0.2
    restart: always
    # Use "always" to start this service when the Docker engine starts
    # or "unless-stopped" to require manual start/stop
    env_file: ./.env
